robot_radius: 0.2

obstacle_layer:
  mark_threshold: 0
  enabled: true
  obstacle_range: 3.8
  raytrace_range: 4.0
  max_obstacle_height: 1.5
  min_obstacle_height: 0.0
  observation_sources: scan
  scan:
    data_type: LaserScan
    topic: scan
    marking: true
    clearing: true
    obstacle_range: 3.8
    raytrace_range: 4.0
    expected_update_rate: 10
    inf_is_valid: true
    observation_persistence: 0.1

