local_costmap:
  global_frame: odom
  publish_frequency: 2.0
  rolling_window: true
  width: 4.0
  height: 4.0
  resolution: 0.05
  plugins:
    - { name: obstacle_layer, type: "costmap_2d::VoxelLayer" }
    - { name: inflation_layer, type: "costmap_2d::InflationLayer" }

  inflation_layer:
    inflation_radius: 0.1
    cost_scaling_factor: 3.0
