shutdown_costmaps: false
controller_frequency: 5.0
clearing_radius: 0.5
controller_patience: 3.0
planner_frequency: 1.0
planner_patience: 5.0
oscillation_timeout: 10.0
oscillation_distance: 0.5

base_local_planner: dwa_local_planner/DWAPlannerROS #"teb_local_planner/TebLocalPlannerROS" # "base_local_planner/TrajectoryPlannerROS" #"teb_local_planner/TebLocalPlannerROS"   # "dwa_local_planner/DWAPlannerROS"
base_global_planner: "navfn/NavfnROS" #alternatives: global_planner/GlobalPlanner, carrot_planner/CarrotPlanner

recovery_behavior_enabled: false1
clearing_rotation_allowed: false
